### ISSUE TITLE
Migrate from `text-format` to `formatting`

### ISSUE THREAD

**Issue by ChShersh** [aelve/fmt#17]
See details here:

* https://github.com/serokell/universum/issues/157

**Comment by neongreen** [comment]
Seems like a good idea. PRs are welcome or I can do it myself at some point but no idea when (I have a shitload of things to read about at $newjob)

**Comment by brandonhamilton** [comment]
What would be the best strategy here?

The `Buildable` class from `formatting` looks like it is a drop-in for the one from `text-format`, so that is an easy replacement.

How should the other functionality from `text-format` be carried over? 
I imagine that delegating to `formatting` and then the wrapping corresponding functions (e.g. `left`, `right`, `expt`) in a [`Formatting.bprint`](https://www.stackage.org/haddock/lts-11.1/formatting-6.3.1/Formatting.html#v:bprint) is not ideal as they would perhaps have a performance cost over the current implementation. Should  the relevant few functions be directly lifted from `text-show` into this codebase? I am also not sure how the [`FormatType`](https://github.com/aelve/fmt/blob/master/lib/Fmt/Internal.hs#L210) class would be adjusted from the [`Data.Text.Format`](https://hackage.haskell.org/package/text-format-0.3.1.1/docs/Data-Text-Format.html) to the [`Formatting.Format`](https://www.stackage.org/haddock/lts-11.1/formatting-6.3.1/Formatting.html#t:Format) type. 

Taking #13 into consideration, I am not sure what the desired path forward here is.

Unfortunately, the dependency on `text-format` is also keeping this package from building on ghc-8.4.

**Comment by neongreen** [comment]
Dammit, `formatting` ships the sources of `text-format` but doesn't expose them :unamused:

**Comment by neongreen** [comment]
https://github.com/chrisdone/formatting/issues/37

**Comment by neongreen** [comment]
@brandonhamilton Sorry, I underestimated the amount of work that needs to be done.

I have a branch where I started porting `fmt` to `Buildable` from `formatting`. It relies on my fork of `formatting` (I'll make a PR to `formatting` when that branch compiles).

That branch is here: https://github.com/aelve/fmt/pull/18. I have given you commit rights: https://github.com/aelve/fmt/invitations.

The `Format` type from `Formatting` is completely different from the one in `Data.Text.Format`, they just happen to share a name. You would have to copy the implementation of `Format` and the corresponding logic into smth like `Fmt.Internal.Format` and reexport it where necessary.

**Comment by neongreen** [comment]
Oh, and the branch above contains a `stack.yaml` which points to GHC 8.4 so if you use stack you'll be able to check whether it compiles on 8.4 or not.

**Comment by neongreen** [comment]
As for #13: ultimately we probably want our own class, because doing UTF8 -> UTF16 whenever you want a `Text` is (likely) unacceptable, but at the same time being able to go via bytestring builder when e.g. writing to a file would bring a performance benefit so we shouldn't give that up either.

I'm not sure how such a class would look like. The simplest solution is to have two methods for Text and ByteString builders, but it's not very good. Having an `IsBuilder` class with two instances (and a polymorphic `build :: IsBuilder a => a` with necessary specialization pragmas) might be better. I'm not sure the specialization will actually work; if it doesn't work, we'll lose lots of performance.
