### ISSUE TITLE
Travis builds using `stack`

### ISSUE THREAD

**Issue by ChShersh** [aelve/fmt#2]
Consider rewriting `.travis.yml` to use `stack` instead how it's done here:
https://github.com/serokell/universum/blob/master/.travis.yml

Now builds are failing: 
https://travis-ci.org/aelve/fmt/jobs/218088641

**Comment by neongreen** [comment]
Builds have been fixed. I won't rewrite .travis.yml to Stack right now because 

1. I think that people still use Cabal for installing libraries more often than they use Stack, and thus testing under Cabal is more important than testing under Stack.
2. Once `fmt` is added to Stackage, we'll get Stackage testing for free.
