### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by neongreen** [aelve/fmt#4]
Will do once `fmt` reaches 0.2. (I don't want people to be stuck with 0.1 for the duration of LTS 8; LTS releases add new packages but don't bump major versions of old ones.)

**Comment by cdornan** [comment]
@neongreen makes complete sense to hold off adding to nightly until you have a stable major version you are happy with. Let me know if I can help with this (I am stackage curator).

I recently used `fmt` in a major new project &mdash; took a little while to get oriented but then it became really clear with a most satisfying result. I am now adding it to our main stack at work &mdash; just so that it is available when needed. Thanks &mdash; love it!

**Comment by neongreen** [comment]
I feel that after #8 has been merged, this is ready to be put on Stackage.

**Comment by neongreen** [comment]
https://github.com/fpco/stackage/pull/2623
